# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signals.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signals.proto',
  package='messenger',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rsignals.proto\x12\tmessenger\")\n\x15user_creation_request\x12\x10\n\x08super_id\x18\x01 \x01(\x03\"6\n\x13send_user_to_client\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\tb\x06proto3'
)




_USER_CREATION_REQUEST = _descriptor.Descriptor(
  name='user_creation_request',
  full_name='messenger.user_creation_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='super_id', full_name='messenger.user_creation_request.super_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=69,
)


_SEND_USER_TO_CLIENT = _descriptor.Descriptor(
  name='send_user_to_client',
  full_name='messenger.send_user_to_client',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='messenger.send_user_to_client.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='messenger.send_user_to_client.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['user_creation_request'] = _USER_CREATION_REQUEST
DESCRIPTOR.message_types_by_name['send_user_to_client'] = _SEND_USER_TO_CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

user_creation_request = _reflection.GeneratedProtocolMessageType('user_creation_request', (_message.Message,), {
  'DESCRIPTOR' : _USER_CREATION_REQUEST,
  '__module__' : 'signals_pb2'
  # @@protoc_insertion_point(class_scope:messenger.user_creation_request)
  })
_sym_db.RegisterMessage(user_creation_request)

send_user_to_client = _reflection.GeneratedProtocolMessageType('send_user_to_client', (_message.Message,), {
  'DESCRIPTOR' : _SEND_USER_TO_CLIENT,
  '__module__' : 'signals_pb2'
  # @@protoc_insertion_point(class_scope:messenger.send_user_to_client)
  })
_sym_db.RegisterMessage(send_user_to_client)


# @@protoc_insertion_point(module_scope)
