name: CI

on: [push]

jobs:
  build-desktop-frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'
    #- uses: actions/cache@v1
    #  with:
    #    path: ~/.nuget/packages
    #    key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
    #    restore-keys: |
    #      ${{ runner.os }}-nuget-
    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format
    
    - name: Check formatting
      run: |
        cd ../
        dotnet format --check
    
    - name: Build the executable
      run: |
        cd DesktopFrontend/DesktopFrontend
        dotnet build
        dotnet format --check
