name: CI

on: [push]

jobs:
  build-desktop-frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.102'
    - name: Install dotnet-format
      run: |
        dotnet tool install -g dotnet-format
        # fix global config
        echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
    
    - name: Check formatting
      run: |
        cd DesktopFrontend
        dotnet format --check
    
    - name: Build the executable
      run: |
        cd DesktopFrontend/DesktopFrontend
        dotnet build
