name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Compile protobuffers
        run: bash ./protobuffers/compile.sh

      - name: Build the executable
        run: |
          cd DesktopFrontend/DesktopFrontend
          dotnet build

  format-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"

      - name: Restore local tools
        working-directory: gatsby  # Error Line Referred to by error response
        uses: xt0rted/dotnet-tool-restore@v1

      - name: Run dotnet format
        id: csharp
        uses: xt0rted/dotnet-format@v1
        with:
          action: "fix"
          args: -w DesktopFrontend/

      - name: Format python code
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive ./Server

      - name: Commit changes
        if: steps.autopep8.outputs.exit-code == 2 || steps.csharp.outputs.has-changes == 'true'
        run: |
          git config --global user.name "Code Formatter"
          git commit -am "Format code"
          git push
