name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Compile protobuffers
        run: bash ./protobuffers/compile.sh

      - name: Build the executable
        run: |
          cd DesktopFrontend/DesktopFrontend
          dotnet build

  format-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"

      - name: Restore local tools
        run: |
          cd DesktopFrontend/
          dotnet tool restore

      - name: Run dotnet format
        id: csharp
        run: |
          cd DesktopFrontend/
          dotnet format --check
          if [ $? -eq 0]; then
            echo "::set-output changed-files=0"
          else
            echo "::set-output changed-files=1"
          fi
          exit 0

      - name: Format python code
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive ./Server

      - name: Commit changes
        if: steps.autopep8.outputs.exit-code == 2 || steps.csharp.outputs.changed-files == 1
        run: |
          echo "python exit ${{ steps.autopep8.outputs.exit-code }}"
          echo "csharp has-changes ${{ steps.csharp.outputs.has-changes }}"
          git config --global user.name "Code Formatter"
          git commit -am "Format code"
          git push
