name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0

      - name: Compile protobuffers
        run: bash ./protobuffers/compile.sh

      - name: Build the executable
        run: |
          cd DesktopFrontend/DesktopFrontend
          dotnet build

  format-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.102"

      - name: Restore local tools
        run: |
          cd DesktopFrontend/
          dotnet tool restore

      - name: Run dotnet format
        id: csharp
        run: |
          cd DesktopFrontend/
          dotnet format --check || CHANGED=1
          if [ "$CHANGED" != "1" ]; then
            echo "::set-output name=changed-files::0"
          else
            echo "::set-output name=changed-files::1"
          fi

      - name: Format python code
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive ./Server

      - name: Print changed files debug
        run: |
          echo "python exit ${{ steps.autopep8.outputs.exit-code }}"
          echo "csharp changed-files ${{ steps.csharp.outputs.changed-files }}"

      - name: Commit changes
        if: steps.autopep8.outputs.exit-code == 2 || steps.csharp.outputs.changed-files == 1
        run: |
          git config --global user.name "Code Formatter"
          git commit -am "Format code"
          git push
